import WhatKnown from "@/comp/WhatKnown";
import MyProjects from "@/comp/work/MyProjects";
import HeroBanner from "@/comp/HeroBanner";

import Head from "next/head";
export default function Work() {
  function line2Text() {
    return (
      <>
        Site's I have build for <span>others</span>.
      </>
    );
  }
  return (
    <>
      <Head>
        <title>Connor | My Work</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroBanner
        bannerImg={2}
        line2={line2Text()}
        line1="It could be your site next."
        link={true}
      />
      <section>
        <MyProjects bg={true} />
        <WhatKnown more={true} bg={false} />
      </section>
    </>
  );
}
